In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from scipy import stats
from sqlalchemy import create_engine

DATABASE_URL = "postgresql://neondb_owner:npg_VOXZBcRohC81@ep-spring-truth-ae312q45.c-2.us-east-2.aws.neon.tech/neondb?sslmode=require&channel_binding=require"
engine = create_engine(DATABASE_URL)

In [2]:
train_delays = pd.read_sql("""
            SELECT * FROM train_delays 
            WHERE delay_min IS NOT NULL
            ORDER BY timestamp
        """, engine)

train_delays

,id,trip_id,stop_id,station_name,timestamp,delay_min,status,direction,stop_sequence,rush_hour,created_at
0,1,126500_N..N31R,R41N,59 St,2025-08-07 01:45:30,21.00,delayed,N,11,None,2025-08-07 02:36:52.776060
1,8,130950_N..S42R,R31S,Atlantic Av-Barclays Ctr,2025-08-07 02:33:07,3.12,delayed,S,16,None,2025-08-07 02:36:52.776060
2,7,129600_N..S42R,N03S,Fort Hamilton Pkwy,2025-08-07 02:36:17,3.78,delayed,S,22,None,2025-08-07 02:36:52.776060
3,2,130150_N..N31R,R17N,34 St-Herald Sq,2025-08-07 02:36:27,-2.05,early,N,23,None,2025-08-07 02:36:52.776060
4,3,131450_N..N31R,R30N,DeKalb Av,2025-08-07 02:36:27,4.95,delayed,N,20,None,2025-08-07 02:36:52.776060
...,...,...,...,...,...,...,...,...,...,...,...
13250,13251,058550_N..S34R,R36S,36 St,2025-09-24 14:30:17,-3.22,early,S,17,None,2025-09-24 14:30:34.680841
13251,13254,060950_N..S34R,R15S,49 St,2025-09-24 14:30:17,-0.22,on_time,S,11,None,2025-09-24 14:30:34.680841
13252,13255,062550_N..S34R,R06S,36 Av,2025-09-24 14:30:17,-1.72,early,S,5,None,2025-09-24 14:30:34.680841
13253,13240,057550_N..N33R,R14N,57 St-7 Av,2025-09-24 14:30:20,-2.17,early,N,19,None,2025-09-24 14:30:34.680841
13254,13239,056600_N..N33R,R09N,Queensboro Plaza,2025-09-24 14:30:22,-0.63,on_time,N,22,None,2025-09-24 14:30:34.680841

In [3]:
weather_data = pd.read_sql("""
            SELECT * FROM weather_data 
            ORDER BY timestamp
        """, engine)
weather_data

,id,timestamp,location_name,latitude,longitude,temp_fahrenheit,feels_like_fahrenheit,temp_min_fahrenheit,temp_max_fahrenheit,weather_main,...,cloudiness,is_precipitation,is_snow,is_extreme_temp,is_high_humidity,is_high_wind,weather_severity_score,sunrise_time,sunset_time,data_timestamp
0,1,2025-08-06 17:00:50.723382,NYC_Manhattan,40.7766,-73.9705,75.07,75.24,72.81,76.78,Clear,...,0,False,False,False,False,False,1,2025-08-06 05:57:26,2025-08-06 20:06:04,2025-08-06 17:00:48
1,2,2025-08-06 17:00:51.750689,NYC_Brooklyn,40.6782,-73.9442,74.88,75.07,72.82,76.82,Smoke,...,0,False,False,False,False,False,1,2025-08-06 05:57:33,2025-08-06 20:05:44,2025-08-06 16:56:15
2,3,2025-08-06 17:00:52.782609,NYC_Queens,40.7253,-73.7857,74.48,74.64,72.73,76.21,Smoke,...,100,False,False,False,False,False,1,2025-08-06 05:56:48,2025-08-06 20:05:13,2025-08-06 16:57:17
3,4,2025-08-06 17:00:53.802942,NYC_Midtown_Manhattan,40.7528,-73.9937,75.16,75.34,72.84,76.82,Clear,...,0,False,False,False,False,False,1,2025-08-06 05:57:35,2025-08-06 20:06:06,2025-08-06 17:00:01
4,5,2025-08-06 17:00:54.825708,NYC_Lower_Manhattan,40.6892,-74.0445,74.73,75.00,73.02,76.50,Clouds,...,40,False,False,False,False,False,1,2025-08-06 05:57:55,2025-08-06 20:06:10,2025-08-06 17:00:54
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4175,4176,2025-09-24 09:45:03.987261,NYC_Manhattan,40.7833,-73.9667,73.06,74.01,70.57,74.95,Clear,...,0,False,False,False,False,False,1,2025-09-24 06:45:31,2025-09-24 18:50:05,2025-09-24 09:36:11
4176,4177,2025-09-24 09:45:05.046989,NYC_Brooklyn,40.6782,-73.9442,73.63,74.61,71.31,75.81,Clear,...,0,False,False,False,False,False,1,2025-09-24 06:45:26,2025-09-24 18:50:00,2025-09-24 09:36:37
4177,4178,2025-09-24 09:45:06.067838,NYC_Queens,40.7258,-73.7907,72.93,74.07,70.79,75.06,Clouds,...,75,False,False,False,True,False,1,2025-09-24 06:44:49,2025-09-24 18:49:23,2025-09-24 09:36:28
4178,4179,2025-09-24 09:45:07.087294,NYC_Midtown_Manhattan,40.7521,-73.9948,73.49,74.44,70.88,75.22,Clear,...,0,False,False,False,False,False,1,2025-09-24 06:45:38,2025-09-24 18:50:12,2025-09-24 09:37:25
4179,4180,2025-09-24 09:45:08.148879,NYC_Lower_Manhattan,40.6892,-74.0445,74.19,75.16,71.51,76.08,Clear,...,0,False,False,False,False,False,1,2025-09-24 06:45:50,2025-09-24 18:50:24,2025-09-24 09:45:08

In [5]:
# Handle timezone conversion (UTC to EST for train_delays)
train_delays['timestamp'] = pd.to_datetime(train_delays['timestamp'])
train_delays['timestamp'] = train_delays['timestamp'].dt.tz_localize('UTC').dt.tz_convert(
    'US/Eastern').dt.tz_localize(None)

weather_data['timestamp'] = pd.to_datetime(weather_data['timestamp'])

# Round timestamps to nearest 15 minutes for matching
train_delays['timestamp_rounded'] = train_delays['timestamp'].dt.round('15min')
weather_data['timestamp_rounded'] = weather_data['timestamp'].dt.round('15min')

merged_data = pd.merge(
            train_delays, weather_data,
            on='timestamp_rounded',
            how='inner',
            suffixes=('_delay', '_weather')
        ).sort_values('timestamp_delay')

merged_data

,id_delay,trip_id,stop_id,station_name,timestamp_delay,delay_min,status,direction,stop_sequence,rush_hour,...,cloudiness,is_precipitation,is_snow,is_extreme_temp,is_high_humidity,is_high_wind,weather_severity_score,sunrise_time,sunset_time,data_timestamp
0,14,038850_N..N35R,R31N,Atlantic Av-Barclays Ctr,2025-08-07 06:55:10,0.67,on_time,N,12,None,...,91,False,False,False,True,False,1,2025-08-07 05:58:25,2025-08-07 20:04:53,2025-08-07 07:00:04
1,14,038850_N..N35R,R31N,Atlantic Av-Barclays Ctr,2025-08-07 06:55:10,0.67,on_time,N,12,None,...,20,False,False,False,False,False,1,2025-08-07 05:58:32,2025-08-07 20:04:32,2025-08-07 06:54:23
2,14,038850_N..N35R,R31N,Atlantic Av-Barclays Ctr,2025-08-07 06:55:10,0.67,on_time,N,12,None,...,40,False,False,False,True,False,1,2025-08-07 05:57:50,2025-08-07 20:04:03,2025-08-07 06:56:59
3,14,038850_N..N35R,R31N,Atlantic Av-Barclays Ctr,2025-08-07 06:55:10,0.67,on_time,N,12,None,...,89,False,False,False,False,False,1,2025-08-07 05:58:34,2025-08-07 20:04:54,2025-08-07 07:00:07
4,14,038850_N..N35R,R31N,Atlantic Av-Barclays Ctr,2025-08-07 06:55:10,0.67,on_time,N,12,None,...,0,False,False,False,False,False,1,2025-08-07 05:58:55,2025-08-07 20:04:58,2025-08-07 07:00:08
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
65882,13207,110600_N..N31R,N02N,8 Av,2025-09-22 18:45:40,3.17,delayed,N,10,evening,...,75,False,False,False,False,False,1,2025-09-22 06:42:51,2025-09-22 18:52:47,2025-09-22 18:44:52
65883,13207,110600_N..N31R,N02N,8 Av,2025-09-22 18:45:40,3.17,delayed,N,10,evening,...,100,False,False,False,False,False,1,2025-09-22 06:43:40,2025-09-22 18:53:36,2025-09-22 18:45:54
65884,13207,110600_N..N31R,N02N,8 Av,2025-09-22 18:45:40,3.17,delayed,N,10,evening,...,75,False,False,False,False,False,1,2025-09-22 06:43:53,2025-09-22 18:53:48,2025-09-22 18:45:55
65870,13205,109350_N..N33R,R31N,Atlantic Av-Barclays Ctr,2025-09-22 18:45:40,1.17,delayed,N,13,evening,...,100,False,False,False,False,False,1,2025-09-22 06:43:35,2025-09-22 18:53:31,2025-09-22 18:44:49
65919,13219,112350_N..S34R,R01S,Astoria-Ditmars Blvd,2025-09-22 18:45:40,2.17,delayed,S,1,evening,...,75,False,False,False,False,False,1,2025-09-22 06:43:53,2025-09-22 18:53:48,2025-09-22 18:45:55